config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'versions/diff'
  end

  root 'cities#index'

  devise_for :users,
             path_names: {
               sign_in: 'login',
               sign_out: 'logout',
               sign_up: 'signup'
             }

  resources :cities, only: [:index, :show]
  resources :categories, only: :show

  resources :excursions, only: :show do
    member do
      delete :erase
    end
  end

  authenticated :user do
    root to: 'admin/excursions#index', as: :user_root

    namespace :admin do
      resources :cities
      resources :categories

      resources :excursions do
        collection do
          get :complete
        end

        resources :versions, only: [] do
          member do
            get :diff
          end
        end
      end
    end
  end
end

app/views/shared/_flash.html.slim
- flash.each do |name, msg|
  - msg = [msg] if msg.class != Array
  - msg.each do |full_message|
    div class="#{flash_class(name)}" role="alert"
      button.close type="button" data-dismiss="alert" aria-label="Close"
        span aria-hidden="true"
          | &times;

      = full_message

app/views/shared/_footer.html.slim
footer.footer
  .container
    .col-md-6
      p.text-left
        | Excursiopedia Test
    .col-md-6
      p.text-right
        | by&ensp;
        = mail_to 'cema.rus@gmail.com', 'cema-sp'

app/views/shared/_menu.html.slim
nav.navbar.navbar-default.navbar-fixed-top  role="navigation"
  .container
    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Excursiopedia Test', root_path, class: 'navbar-brand'

    #navbar.collapse.navbar-collapse
        .navbar-right
          = render 'shared/menu_items'

app/views/shared/_menu_items.html.slim
ul.nav.navbar-nav
  /li = link_to 'Excursions', excursions_path
  li = link_to 'Cities', cities_path
  /li = link_to 'Categories', categories_path

  - unless user_signed_in?
    li = link_to 'Log in', new_user_session_path
    li = link_to 'Sign up', new_user_registration_path
    
  - else
    li class="dropdown"
      a.dropdown-toggle href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
        | Manage
        span.caret
      ul class="dropdown-menu"
        li = link_to 'Excursions', admin_excursions_path
        li = link_to 'Cities', admin_cities_path
        li = link_to 'Categories', admin_categories_path

        - if current_user.is_manager?
          li = link_to 'Complete!', complete_admin_excursions_path

    li class="dropdown"
      a.dropdown-toggle href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
        = "#{current_user.name} (#{current_user.type})" 
        span.caret
      ul class="dropdown-menu"
        li
          = link_to 'Profile', edit_user_registration_path
        li role="separator" class="divider"
        li
          = link_to 'Log out', destroy_user_session_path, method: :delete