config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'versions/diff'
  end

  root 'cities#index'

  devise_for :users,
             path_names: {
               sign_in: 'login',
               sign_out: 'logout',
               sign_up: 'signup'
             }

  resources :cities, only: [:index, :show]
  resources :categories, only: :show

  resources :excursions, only: :show do
    member do
      delete :erase
    end
  end

  authenticated :user do
    root to: 'admin/excursions#index', as: :user_root

    namespace :admin do
      resources :cities
      resources :categories

      resources :excursions do
        collection do
          get :complete
        end

        resources :versions, only: [] do
          member do
            get :diff
          end
        end
      end
    end
  end
end

app/models/excursion.rb
class Excursion < ActiveRecord::Base
  has_paper_trail on: :update, only: :description

  validates :name,
            presence: true,
            length: { minimum: 2, maximum: 120 }

  validates :city_id,
            presence: true

  validates :category_ids,
            presence: true,
            length: { minimum: 1 }

  belongs_to :city
  has_and_belongs_to_many :categories, -> { uniq }

  scope :published, -> { where(published: true) }
end

app/controllers/admin/excursions_controller.rb
class Admin::ExcursionsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!,
                except: [:index, :show, :edit, :update, :complete]

  before_action :set_paper_trail_whodunnit, only: :update

  after_action :verify_authorized

  before_action :set_excursion, only: [:show, :edit, :update, :destroy]

  # GET /excursions
  def index
    @excursions = Excursion.all
    authorize Excursion
  end

  # GET /excursions/1
  def show
    authorize @excursion
  end

  # GET /excursions/new
  def new
    @excursion = Excursion.new
    authorize @excursion
  end

  # GET /excursions/1/edit
  def edit
    authorize @excursion
  end

  # GET /excursions/complete
  def complete
    authorize Excursion
    @completing = true
    @excursion = (
      Excursion.where(description: nil).first ||
      Excursion.where(description: '').first ||
      Excursion.where(description: ' ').first
    )

    if @excursion
      render :edit
    else
      redirect_to admin_excursions_path
    end
  end

  # POST /excursions
  def create
    @excursion = Excursion.new(excursion_params)
    authorize @excursion

    respond_to do |format|
      if @excursion.save
        format.html { redirect_to [:admin, @excursion], notice: 'Excursion was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /excursions/1
  def update
    authorize @excursion
    respond_to do |format|
      if @excursion.update(excursion_params)
        format.html do
          if params[:completing]
            redirect_to(action: :complete)
            return
          else
            redirect_to [:admin, @excursion],
                        notice: 'Excursion was successfully updated.'
          end
        end
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /excursions/1
  def destroy
    authorize @excursion
    @excursion.destroy
    respond_to do |format|
      format.html { redirect_to admin_excursions_url, notice: 'Excursion was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_excursion
    @excursion = Excursion.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def excursion_params
    params
      .require(:excursion)
      .permit(:name, :description, :published, :city_id, category_ids: [])
  end
end

app/controllers/excursions_controller.rb
class ExcursionsController < ApplicationController
  # GET /excursions/1
  def show
    @excursion = Excursion.find(params[:id])

    session[:visited_excursions] ||= []
    session[:visited_excursions].reject! { |id| id == params[:id].to_i }

    @visited_excursions =
      session[:visited_excursions]
      .dup
      .reverse[0, 3]
      .map { |id| Excursion.find(id) }

    session[:visited_excursions] << @excursion.id
  end

  # DELETE /excursions/1
  def erase
    session[:visited_excursions].reject! { |id| id == params[:id].to_i }
    redirect_to :back
  end
end

app/views/admin/excursions/_form.html.slim
= simple_form_for([:admin, @excursion]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, \
      palceholder: 'Excursion name', \
      hint: '2 - 120 chars', \
      required: true

    = f.input :description, \
      placeholder: 'Short description'

    = f.input :published
    = f.association :city, \
      prompt: 'Select city', \
      include_blank: false

    = f.association :categories, \
      include_blank: false, \
      hint: 'You can select multiple values, just start typing'

    = hidden_field_tag("completing", true) if local_assigns[:completing] && completing

  .form-actions
    = f.button :submit, \
      class: ['btn', 'btn-primary']

javascript:
  $( "#excursion_category_ids" ).select2({
    placeholder: "Select categories",
    theme: "bootstrap"
  });

app/views/admin/excursions/edit.html.slim
.col-md-4.col-md-offset-4
  h1 Editing excursion

  #flash
    = render 'shared/flash'

  == render 'form', completing: @completing

  = link_to 'Show', [:admin, @excursion]
  '|
  = link_to 'Back', admin_excursions_path

app/views/admin/excursions/index.html.slim
.col-md-12
  #flash
    = render 'shared/flash'

  .table-responsive
    table.table.table-hover.table-striped
      caption
        h1 Excursions
      thead
        tr
          th Name
          th Description
          th Published
          th City
          th Categories
          th

      tbody
        - @excursions.each do |excursion|
          tr
            td = link_to excursion.name, [:admin, excursion]
            td = excursion.description ? (excursion.description[0, 32] + '...') : ''
            td = excursion.published ? '&#9733;'.html_safe : '&#9734;'.html_safe
            td = excursion.city.name
            td = excursion.categories.pluck(:name).join(', ')
            td
              - if policy(excursion).edit?
                | &ensp;
                = link_to 'Edit', edit_admin_excursion_path(excursion)

              - if policy(excursion).destroy?
                | &ensp;
                = link_to 'Destroy', excursion, data: {:confirm => 'Are you sure?'}, :method => :delete

  br

  - if policy(Excursion).new?
    = link_to 'Add Excursion', new_admin_excursion_path, class: ['btn', 'btn-default']

app/views/admin/excursions/new.html.slim
.col-md-4.col-md-offset-4
  h1 New excursion

  #flash
    = render 'shared/flash'

  == render 'form'

  = link_to 'Back', admin_excursions_path

app/views/admin/excursions/show.html.slim
.col-md-8.col-md-offset-2
  #flash
    = render 'shared/flash'

  p
    strong Name:&ensp;
    = @excursion.name
  p
    strong Description:&ensp;
    = @excursion.description
  p
    strong Published:&ensp;
    = @excursion.published
  p
    strong City:&ensp;
    = @excursion.city.name

  p
    strong Categories:&emsp;
    = @excursion.categories.pluck(:name).join(', ')

  .table-responsive
    table.table.table-hover.table-striped
      caption
        h1 Versions
      thead
        tr
          th Date
          th Author
          th

      tbody
        - @excursion.versions.reverse.each do |version|
          tr
            td = version.created_at
            td = User.find(version.whodunnit).name
            td
              = link_to 'Diff', diff_admin_excursion_version_path(@excursion, version)

  br

  - if policy(@excursion).edit?
    = link_to 'Edit', edit_admin_excursion_path(@excursion), class: ['btn', 'btn-default']

  = link_to 'Back', admin_excursions_path, class: ['btn', 'btn-default']