config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'versions/diff'
  end

  root 'cities#index'

  devise_for :users,
             path_names: {
               sign_in: 'login',
               sign_out: 'logout',
               sign_up: 'signup'
             }

  resources :cities, only: [:index, :show]
  resources :categories, only: :show

  resources :excursions, only: :show do
    member do
      delete :erase
    end
  end

  authenticated :user do
    root to: 'admin/excursions#index', as: :user_root

    namespace :admin do
      resources :cities
      resources :categories

      resources :excursions do
        collection do
          get :complete
        end

        resources :versions, only: [] do
          member do
            get :diff
          end
        end
      end
    end
  end
end

app/models/city.rb
class City < ActiveRecord::Base
  validates :name,
            presence: true,
            length: { minimum: 2, maximum: 32 }

  has_many :excursions, dependent: :destroy

  scope :has_excursions,
        -> { includes(:excursions).select { |c| c.excursions.published.count > 0 } }
end

app/controllers/admin/cities_controller.rb
class Admin::CitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!, except: [:index, :show]

  after_action :verify_authorized

  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  def index
    @cities = City.all
    authorize City
  end

  # GET /cities/1
  def show
    authorize @city
  end

  # GET /cities/new
  def new
    @city = City.new
    authorize @city
  end

  # GET /cities/1/edit
  def edit
    authorize @city
  end

  # POST /cities
  def create
    @city = City.new(city_params)
    authorize @city

    respond_to do |format|
      if @city.save
        format.html { redirect_to admin_cities_path, notice: 'City was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /cities/1
  def update
    authorize @city
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to admin_cities_path, notice: 'City was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /cities/1
  def destroy
    authorize @city
    @city.destroy
    respond_to do |format|
      format.html { redirect_to admin_cities_url, notice: 'City was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_city
    @city = City.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def city_params
    params.require(:city).permit(:name)
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  # GET /cities
  def index
    @cities = City.has_excursions
  end

  # GET /cities/1
  def show
    @city = City.find(params[:id])
  end
end

app/views/admin/cities/_form.html.slim
= simple_form_for([:admin, @city]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, \
      placeholder: 'Moscow', \
      hint: '2 - 32 chars', \
      required: true

  .form-actions
    = f.button :submit, \
      class: ['btn', 'btn-primary']

app/views/admin/cities/edit.html.slim
.col-md-4.col-md-offset-4
  h1 Editing city

  #flash
    = render 'shared/flash'

  == render 'form'

  = link_to 'Show', [:admin, @city]
  '|
  = link_to 'Back', admin_cities_path

app/views/admin/cities/index.html.slim
.col-md-8.col-md-offset-2
  #flash
    = render 'shared/flash'

  .table-responsive
    table.table.table-hover.table-striped
      caption
        h1 Cities
      thead
        tr
          th Name
          th

      tbody
        - @cities.each do |city|
          tr
            td = city.name
            td
              - if policy(city).edit?
                = link_to 'Edit', edit_admin_city_path(city)

              - if policy(city).destroy?
                | &ensp;
                = link_to 'Destroy', [:admin, city], \
                  data: {:confirm => 'Are you sure?'}, \
                  :method => :delete

  br

  - if policy(City).new?
    = link_to 'Add City', new_admin_city_path, class: ['btn', 'btn-default']

app/views/admin/cities/new.html.slim
.col-md-4.col-md-offset-4
  h1 New city

  #flash
    = render 'shared/flash'

  == render 'form'

  = link_to 'Back', admin_cities_path

app/views/admin/cities/show.html.slim
.col-md-4.col-md-offset-4
  #flash
    = render 'shared/flash'

  p
    strong Name:
    = @city.name

  - if policy(@city).edit?
    = link_to 'Edit', edit_admin_city_path(@city)
    '|

  = link_to 'Back', admin_cities_path