config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'versions/diff'
  end

  root 'cities#index'

  devise_for :users,
             path_names: {
               sign_in: 'login',
               sign_out: 'logout',
               sign_up: 'signup'
             }

  resources :cities, only: [:index, :show]
  resources :categories, only: :show

  resources :excursions, only: :show do
    member do
      delete :erase
    end
  end

  authenticated :user do
    root to: 'admin/excursions#index', as: :user_root

    namespace :admin do
      resources :cities
      resources :categories

      resources :excursions do
        collection do
          get :complete
        end

        resources :versions, only: [] do
          member do
            get :diff
          end
        end
      end
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name,
            presence: true,
            length: { minimum: 2, maximum: 32 }

  has_and_belongs_to_many :excursions, -> { uniq }
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!, except: [:index, :show]
  after_action :verify_authorized

  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    authorize Category
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    authorize @category
  end

  # GET /categories/new
  def new
    @category = Category.new
    authorize @category
  end

  # GET /categories/1/edit
  def edit
    authorize @category
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    authorize @category

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_url, notice: 'Category was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    authorize @category
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_categories_url, notice: 'Category was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    authorize @category
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories/1
  def show
    @category = Category.find(params[:id])
  end
end

app/views/admin/categories/_form.html.slim
= simple_form_for([:admin, @category]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, \
      placeholder: 'Nature', \
      hint: '2 - 32 chars', \
      required: true

  .form-actions
    = f.button :submit, \
      class: ['btn', 'btn-primary']

app/views/admin/categories/edit.html.slim
.col-md-4.col-md-offset-4
  h1 Editing category

  #flash
    = render 'shared/flash'

  == render 'form'

  = link_to 'Show', [:admin, @category]
  '|
  = link_to 'Back', admin_categories_path

app/views/admin/categories/index.html.slim
.col-md-8.col-md-offset-2
  #flash
    = render 'shared/flash'

  .table-responsive
    table.table.table-hover.table-striped
      caption
        h1 Categories
      thead
        tr
          th Name
          th

      tbody
        - @categories.each do |category|
          tr
            td = category.name
            td
              - if policy(category).edit?
                = link_to 'Edit', edit_admin_category_path(category)

              - if policy(category).destroy?
                | &ensp;
                = link_to 'Destroy', [:admin, category], data: {:confirm => 'Are you sure?'}, :method => :delete

  br

  - if policy(Category).new?
    = link_to 'Add Category', new_admin_category_path, class: ['btn', 'btn-default']

app/views/admin/categories/new.html.slim
.col-md-4.col-md-offset-4
  h1 New category

  #flash
    = render 'shared/flash'

  == render 'form'

  = link_to 'Back', admin_categories_path

app/views/admin/categories/show.html.slim
.col-md-4.col-md-offset-4
  #flash
    = render 'shared/flash'

  p
    strong Name:
    = @category.name

  - if policy(@category).edit?
    = link_to 'Edit', edit_admin_category_path(@category)
    '|

  = link_to 'Back', admin_categories_path